# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Add share.dmhy.org RSS

on:
  workflow_dispatch:
    inputs:
      rss_key:
        description: 'bangumi name'
        required: true
      rss_url:
        description: 'rss url'
        required: true
permissions:
  contents: write

jobs:
  add_rss:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
      with:
        branch: ${{ github.ref }}
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        version: "25.3"
    - name: Generage Protobuf
      run: ./generage_proto.sh
    - name: Add RSS
      env:
        RSS_KEY: ${{ inputs.rss_key }}
        RSS_URL: ${{ inputs.rss_url }}
      run: python src/add_dmhy_rss_config.py -c '.env.prod'
    - name: Check updates
      id: check_updates
      run: |
        if [[ -z $(git status --porcelain) ]]; then
          echo "no updates"
          echo "no_updates=true" >> $GITHUB_OUTPUT
          exit
        else
          echo "changes detected"
          echo "no_updates=false" >> $GITHUB_OUTPUT
        fi
    - name: Commit files
      if: steps.check_updates.outputs.no_updates == 'false'
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add storage
        git commit -a -m "manually add bangumi rss"
    - name: Push changes
      if: steps.check_updates.outputs.no_updates == 'false'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}